#!/usr/bin/env node
/**
 * load-index.js
 * Load a routing digest from forgebee/INDEX.md as additionalContext on SessionStart.
 *
 * The index gives Claude a routing map across 115+ surfaces (skills, agents,
 * commands) without having to scan each frontmatter individually.
 *
 * The whole file is ~20KB, which the harness rejects as oversized additionalContext —
 * it persists the payload to disk and injects only a short preview, so every section
 * past the first ~2KB (including the whole WordPress stack) never reached the session.
 * We therefore emit a digest: the Quick Triage table, the agent sections matching the
 * detected stack, and a pointer to read the full file when routing is unclear.
 *
 * Generated by scripts/build-index.js — never hand-edit INDEX.md.
 */

const fs = require('fs');
const path = require('path');
const {
  findForgebeeRoot,
  getProjectDir,
  detectProjectStacks,
  output,
} = require('./_common.js');

const MAX_BYTES = 3500;

// Agent sections in INDEX.md worth pinning when the project uses that stack.
const STACK_SECTIONS = {
  wordpress: 'WordPress Stack',
  nextjs: 'Next.js Stack',
  supabase: 'Database/Backend Stack',
  llm: 'LLM Stack',
};

/**
 * Pull one section out of INDEX.md by heading prefix, without its heading.
 * Matches "## " or "### " and stops at the next heading of the same or higher level.
 */
function extractSection(content, title) {
  const lines = content.split('\n');
  const start = lines.findIndex(
    l => /^#{2,3} /.test(l) && l.replace(/^#{2,3} /, '').trim().startsWith(title)
  );

  if (start === -1) {
    return '';
  }

  const level = lines[start].match(/^#+/)[0].length;
  const body = [];

  for (let i = start + 1; i < lines.length; i++) {
    const heading = lines[i].match(/^(#{1,6}) /);
    if (heading && heading[1].length <= level) {
      break;
    }
    body.push(lines[i]);
  }

  // Drop the trailing "---" rule that separates INDEX.md sections.
  return body
    .join('\n')
    .replace(/\n+---\s*$/, '')
    .trim();
}

function main() {
  try {
    const forgebeeRoot = findForgebeeRoot();
    const indexFile = path.join(forgebeeRoot, 'INDEX.md');

    if (!fs.existsSync(indexFile)) {
      // INDEX.md missing — never block session, just exit silently.
      // The user can run `node scripts/build-index.js` to generate it.
      process.exit(0);
    }

    const content = fs.readFileSync(indexFile, 'utf8');
    const triageTable = extractSection(content, 'Quick Triage');

    const parts = [
      '## ForgeBee Routing Index (digest of forgebee/INDEX.md)',
      '',
      'Route user intent to a skill/agent/command before starting work.',
      `Full index (all skills, agents, commands): read \`${path.relative(getProjectDir(), indexFile)}\`.`,
      '',
    ];

    if (triageTable) {
      parts.push('### Quick Triage', '', triageTable, '');
    }

    for (const stack of detectProjectStacks()) {
      const section = extractSection(content, STACK_SECTIONS[stack]);
      if (section) {
        parts.push(`### ${STACK_SECTIONS[stack]} (this project)`, '', section, '');
      }
    }

    let wrapped = parts.join('\n');

    // Hard ceiling — an oversized payload gets dropped, which is the bug this fixes.
    if (Buffer.byteLength(wrapped, 'utf8') > MAX_BYTES) {
      wrapped =
        wrapped.slice(0, MAX_BYTES) +
        `\n\n_Digest truncated — read ${path.relative(getProjectDir(), indexFile)} for the rest._`;
    }

    output({
      hookSpecificOutput: {
        hookEventName: 'SessionStart',
        additionalContext: wrapped,
      },
    });
  } catch (e) {
    // Never block session start
    process.exit(0);
  }
}

main();
